version: '3'
services:
  app:
    container_name: drivent_development
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgresDB
      - redisDB
    volumes:
      - .:/app

  postgresDB:
    image: postgres:13
    container_name: postgresDB
    env_file:
      - .env
    ports:
      - 5433:${POSTGRES_PORT}
    restart: always
    volumes:
      - progresDB:/data/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}

  redisDB:
    image: redis
    container_name: redisDB
    env_file:
      - .env
    ports:
      - 6380:6379
    restart: always
    volumes:
      - redisDB:/data/redis

volumes:
  progresDB:
  redisDB:
